apiVersion: v1
kind: Pod
metadata:
  name: devops
  labels:
    app: devops
spec:
  containers:
    - name: devops
      image: immassive/devops:7
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
